### ISSUE TITLE
The order of MPOB slices

### ISSUE THREAD

**Issue by leihouyeung** [JEFworks-Lab/STdeconvolve#18]
Hi @bmill3r , thanks for your excellent work.  I saw that the MERFISH MPOB data are split as several different slices by the column called 'Bregma' and there are multimuple values which confused me. They are "-0.04" "-0.09" "-0.14" "-0.19" "-0.24" "-0.29" "0.01"  "0.06"  "0.11"  "0.16"  "0.21"  "0.26". Could you help me sort these so that I could know the correct order from posterior to anterior? Thanks again for your time.

**Comment by bmill3r** [comment]
Hi @leihouyeung,

Thanks so much for reaching out and using `STdeconvolve`! The order of the MERFISH MPOA bregma slices as shown in Supplemental Figure S1 of the paper are `-0.04 -0.09 -0.14 -0.19 -0.24 -0.29  0.01  0.06  0.11  0.16  0.21  0.26` posterior to anterior. Hope this helps and let me know if you have any other questions! FYI the data comes from this [paper](https://www.science.org/doi/abs/10.1126/science.aau5324)

Brendan
