### ISSUE TITLE
Question related to 10x Visium STdeconvolve

### ISSUE THREAD

**Issue by JoyOtten** [JEFworks-Lab/STdeconvolve#22]
Hi,

I have a question related to STdeconvolve and if it's possible to fit the model on multiple samples at the same time? I have in total 16 samples that are all similar/equal to one another. Where I would like to run STdeconvolve and fit the model on all 16 samples. I've created a script for that to run it on the spatial raw data but I was wondering if the model can be used on 16 samples at the same time and still detect differences in cell type compositions between samples if there are any? The hypothesis is that we do not have cell type differences between the samples. However, we would like to know where which cell type is located within our samples.

Thank you,
Joy

**Comment by bmill3r** [comment]
Hi @JoyOtten,

Thanks so much for using `STdeconvolve` and so sorry for the delay in my response!

As it happens, I just responded to a similar question [here](https://github.com/JEFworks-Lab/STdeconvolve/issues/21#issuecomment-1236422952), which hopefully provides some answers for you.

Let me know if that helps or if you have any additional questions and happy to help answer them,
Brendan
