### ISSUE TITLE
deconvolved cell-types to seurat object

### ISSUE THREAD

**Issue by AteeqMKhaliq** [JEFworks-Lab/STdeconvolve#27]
Hi Brendan,
Sorry for bothering you again, I have deconvolved the cell types and I have compared them in terms of clustering the barcodes transcriptionally as detailed in 10X tutorials. Now I have 18 beautiful clusters, is there a way I can add or convert or create a 2D t-SNE embedding into a Seurat object? I wanted to do the downstream analysis between these clusters. Sorry if I am asking too many questions, but trust me you are my last hope. Thanks again for creating such a beautiful tool.
Best wishes,
Regards,
AK

**Comment by bmill3r** [comment]
Hi @AteeqMKhaliq,

Glad that you are finding `STdeconvolve` useful! Could you clarify a little bit more about the downstream analyses you would like to do? When you say add a 2D t-SNE into a Seurat object, you mean to perform t-SNE on the barcodes of your spatial datasets based on their gene counts? If that is the case, and your spatial data is already in a Seurat object, I believe Seurat already has a [built in function to perform a t-SNE](https://satijalab.org/seurat/reference/runtsne#run-t-distributed-stochastic-neighbor-embedding). The result of this should be placed in a slot in the Seurat object for dimensionality reductions.

Let me know if this helps or you have more questions,
Brendan

**Comment by AteeqMKhaliq** [comment]
Thank you Brendan for the quick reply, I did dimensionality reduction on the counts matrix, and now I have 18 clusters, I wanted to run pathway analysis between these clusters and I feel Seurat makes it a bit easier for me to handle. So, can I include the dimensionality reductions in my existing Seurat object, if yes can you please let me know how to go about it? 
Thanks again
Best,
AK

**Comment by bmill3r** [comment]
Hi @AteeqMKhaliq,

Yes, Seurat does have built in functions to perform dimensionality reductions like t-SNE. Check out one of their tutorials [here](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html#run-non-linear-dimensional-reduction-umap-tsne-). Also the slot [DimReduc](https://github.com/satijalab/seurat/wiki/DimReduc) will contain the outputs of the reduction that you will want. I am not a developer of Seurat, however, so you may want to look into the tutorials for this package specifically and reach out to the respective authors via their own GitHub page or website.

Hope this helps,
Brendan

**Comment by AteeqMKhaliq** [comment]
Thank you, i have solved this, thanks for your help.

**Comment by cathalgking** [comment]
Hi @AteeqMKhaliq 

I would also be interested in using this package to deconvolve the cell types and then perform the remaining analysis with Seurat. Can I ask how you did this? Thanks
