### ISSUE TITLE
Cell type specific counts, and testing between conditions

### ISSUE THREAD

**Issue by Dillon214** [JEFworks-Lab/STdeconvolve#42]
Hello STdeconvolve devs,

I am looking for a good tool to use in my analysis of a large visium dataset, consisting of brain tissue from 2 different conditions. Ultimately, I am interested in comparing gene expression for a given cell type across these conditions.

I think STdeconvolve would be the perfect tool for this assuming it produces cell type specific counts that can be plugged into DE testing algorithms. Is this a feature of STdeconvolve, and if so, do you have any advice for how I can extract said counts and normalize them for DE testing? I have noticed it implemented in certain ref-based deconvolution algorithms, but I am specifically interested in the reference-free approach of this tool. Any advice would be appreciated!

-Dillon

**Comment by bmill3r** [comment]
Hi @Dillon214,

Thanks for your interest in STdeconvolve! If you look at the example on the main page, you'll see that STdeconvolve returns a  deconvolved cell by gene expression matrix, which I think is what you are after?

```
deconGexp <- results$beta
```

We don't have DE testing between cell types built in directly, but if you check out our tutorial on applying STdeconvolve to Visium data (https://github.com/JEFworks-Lab/STdeconvolve/blob/devel/docs/visium_10x.md) you'll see that we identify DE genes between the deconvolved cell types in one sample. Perhaps you could use a similar approach to test for DE genes between two samples.

Hope this helps,
Brendan
