### ISSUE TITLE
Clustering a specific cell type

### ISSUE THREAD

**Issue by Dillon214** [JEFworks-Lab/STdeconvolve#44]
Hello Stdeconvolve developers,

I am interested in using Stdeconvolve to better understand a large spatial dataset I'm working with, and am most excited about its ability to generate cell type specific transcriptomes. However, when I tried it out, I had some difficulty isolating a cell type that interests me most. Would it be possible to tailor the analysis pipeline to focus in on a cell type I care most about, using known markers for that given cell type? I would be grateful for any help with this. 

-Dillon

**Comment by bmill3r** [comment]
Hi @Dillon214,

Thanks for your interest in STdeconvolve! While we do not have a semi-supervised approach set up, what I could recommend trying is to make sure that the specific marker genes for your cell type of interest are included in the input spot x gene count matrix after feature selection. By default, STdeconvolve first feature selects for the most informative genes and uses the variation in the expression of these genes to identify putative cell types. But if you ensure that your marker genes of interest are in this selected feature matrix, then this might increase the likelihood of STdeconvolve identifying topics enriched in these marker genes.

Hope this helps and let me know if you have any other questions,
Brendan
