### ISSUE TITLE
How to know what are topics when plotting pie charts on that pixel?

### ISSUE THREAD

**Issue by Shikari666** [JEFworks-Lab/STdeconvolve#45]
I tried different ways to define the topic cell type but not mentioned in the algorithm I guess.Wanted to ask you guys If we can actually say what a topic here instead of groups.

**Comment by bmill3r** [comment]
Hi @Shikari666, 

Thanks for your interest in STdeconvolve. I would recommend checking out some of the tutorials we have available, particularly the ones like "Annotating deconvolved cell types". It should provide several different approaches you can take to help identify the decontrolled cell types.

Hope this helps,
Brendan
