### ISSUE TITLE
Analyze specific area of the slide

### ISSUE THREAD

**Issue by chfloudas** [JEFworks-Lab/STdeconvolve#46]
Hi there, thanks for developing STdeconvolve. Is there a way to define a particular area on the slide and analyze only that, e.g. in case the slide has two sections of tissue  or within the same section?

**Comment by bmill3r** [comment]
Hi @chfloudas,

Thanks for you interest in `STdeconvolve`! We don't have a function to specifically lasso regions of interest for analysis. However, you can subset the particular spots of interest based on their coordinates in the `pos` matrix. Then you can use these selected spot indices to select the equivalent rows in the `counts` matrix.

Hope this helps,
Brendan

**Comment by chfloudas** [comment]
Hi @bmill3r, thanks for the reply! Would the way to do this be found in https://github.com/JEFworks-Lab/STdeconvolve/issues/39?

**Comment by bmill3r** [comment]
Hi @chfloudas,

That issue is more about rotating the dataset, but using the `pos` matrix, you can select the locations of interest by filtering on the `x` and `y` coordinates.

Brendan
