### ISSUE TITLE
ST deconvolve analyses with replicates

### ISSUE THREAD

**Issue by dcare91** [JEFworks-Lab/STdeconvolve#47]
Dear all,

I am writing regarding a way of plotting results when having 2 replicates of the same condition. I am comparing healthy condition (n=2) with pathological condition (n=2), meaning 4 brain slices in total. I have run them individually first. I have used a K=9 (identifying 9 topics each). The most upregulated gene gives a name to each Topic and generally, due to the high variability in sample prep, it is hard to identify the same Topic gene label. Interestingly, one topic appeared to be present in both replicates of my pathological condition and not in my healthy one. Now I would like to plot this result but I don't have any good idea to highlight this result. Have you thought how to improve such thing when having biological replicates?

Thank you so much in advance,
Best,

@dcare91

**Comment by bmill3r** [comment]
Hi @dcare91,

Thanks for your interest in STdeconvolve and sorry for the delayed response. If I understand your goal properly, you would like to plot both replicates and highlight the same topic in each? Typically when showing topics that are shared across different samples when plotting, I ensure that the same topic is indicated by the same color in both scatterpie plots. You should be able to specify the topic colors in `vizAllTopics()`. For some examples you can check out one of our guides here: https://github.com/JEFworks-Lab/STdeconvolve/blob/devel/docs/additional_features.md.

We recently published a paper utilizing STdeconvolve in which we also looked for similar topics across different replicates. You can check out the paper here: https://www.nature.com/articles/s41598-023-48213-2 and in particular supplementary figures 7 and 8. 

Does this help?

Brendan

**Comment by dcare91** [comment]
Dear Brendan,

I am sorry for the delayed answer. I was reanalysing all my data again in a better way and I spot again an interesting finding coming from your method.
It would be nice to have a meeting to discuss what we have done and what you think about it.
Is that possible for you to e-meet some of these days?

Best,
Davide

Davide Caredio
PhD candidate - Institute of Neuropathology
University of Zurich
Schmelzbergstrasse, 12
CH-8091 Zurich

On 6 Jan 2024, at 19:45, bmill3r ***@***.***> wrote:



Hi @dcare91<https://github.com/dcare91>,

Thanks for your interest in STdeconvolve and sorry for the delayed response. If I understand your goal properly, you would like to plot both replicates and highlight the same topic in each? Typically when showing topics that are shared across different samples when plotting, I ensure that the same topic is indicated by the same color in both scatterpie plots. You should be able to specify the topic colors in vizAllTopics(). For some examples you can check out one of our guides here: https://github.com/JEFworks-Lab/STdeconvolve/blob/devel/docs/additional_features.md.

We recently published a paper utilizing STdeconvolve in which we also looked for similar topics across different replicates. You can check out the paper here: https://www.nature.com/articles/s41598-023-48213-2 and in particular supplementary figures 7 and 8.

Does this help?

Brendan

**Comment by bmill3r** [comment]
Hi @dcare91,

My bandwidth is limited these days (and no longer associated with the JEFworks lab), however, feel free to contact me through my personal website located on my profile page (note that it is a bit outdated) and we can take this conversation off GitHub. I can try to find time to discuss further.

Thanks,
Brendan
