### ISSUE TITLE
mOB dataset

### ISSUE THREAD

**Issue by caucheteux** [JEFworks-Lab/STdeconvolve#48]
Hello,
I am using Spatial 10X Visium data and I have been able to load my data most of the time, except when your example is set with the mOB or data(mOB) dataset.  It works great and is very useful.  Is there a way to understand what was done to obtain the mOB included in STdeconvolve or any other repositories as if I was processing it from a Spatial 10X Visium SpaceRanger output? Thank you!
Best regards,

**Comment by Umaarasu** [comment]
I also have the same comment as @caucheteux. Would be great if you could do this :)

**Comment by bmill3r** [comment]
Hi @caucheteux 

Thanks so much for using `STdeconvolve` and thanks for your question. You can find links to the datasets used and how they were processed in the Methods, Data Availability, and in the Supplementary Methods. In terms of processing SpaceRanger outputs, I would recommend checking out some of our tutorials on GitHub, particularly "Analysis of 10X Visium Data". You can read them in with the `SpatialExperiment`library.

Hope this helps,
Brendan
